#Note: login-server needs to be manually set, and the 'REGISTRY_USERNAME' and 'REGISTRY_PASSWORD' secrets are required to be added into GitHub Secrets. See these docs for details: https://github.com/Azure/docker-login
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  Build_Stage_Build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - # "Note: login-server needs to be manually set, and the 'REGISTRY_USERNAME' and 'REGISTRY_PASSWORD' secrets are required to be added into GitHub Secrets. See these docs for details: https://github.com/Azure/docker-login"
      name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ''
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build --file **/Dockerfile serviceconnection_dockerhub ghoshasish99/azuredevops-bootcamp --tags latest
        docker push --file **/Dockerfile serviceconnection_dockerhub ghoshasish99/azuredevops-bootcamp --tags latest
    - run: Copy '/docker-compose.yml' '${{ github.workspace }}'
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}
        name: drop
                    